# Автономный запуск Studio: Play без ручного Rojo Connect / HTTP Settings
# Usage: .\open-studio.ps1
#        .\open-studio.ps1 -Live          live-синк Rojo (нужен Connect)
#        .\open-studio.ps1 -BuildPackaged ещё и пересобрать map-пакет
#
# По умолчанию: собирает BridgeDefense_Commission.rbxl со ВСЕМИ скриптами
# + StudioProfiles, поднимает LogServer/Watch-Logs, ставит плагин Persist.
# Тебе остаётся только F5 (Play).

param(
    [switch]$Live,
    [switch]$BuildPackaged
)

$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
if ($args -contains '-Live') { $Live = $true }
if ($args -contains '-BuildPackaged') { $BuildPackaged = $true }

$Rojo = Join-Path $env:USERPROFILE '.local\bin\rojo.exe'
$Lune = Join-Path $env:USERPROFILE '.local\bin\lune.exe'
$Place2 = Join-Path $ProjectRoot 'Commission_place (2).rbxl'
$Place1 = Join-Path $ProjectRoot 'Commission_place (1).rbxl'
$Packaged = Join-Path $ProjectRoot 'BridgeDefense_Commission.rbxl'
$RojoProject = Join-Path $ProjectRoot 'commission-place.project.json'
$LobbyProject = Join-Path $ProjectRoot 'lobby.project.json'
$PluginSrc = Join-Path $ProjectRoot 'tools\BridgeDefensePersist.plugin.lua'
$PluginsDir = Join-Path $env:LOCALAPPDATA 'Roblox\Plugins'

if (-not (Test-Path $Rojo)) {
    Write-Host 'Rojo not found. Run .\install-tools.ps1 first.' -ForegroundColor Red
    exit 1
}

function Install-PersistPlugin {
    if (-not (Test-Path -LiteralPath $PluginSrc)) {
        Write-Host 'WARN: Persist plugin source missing' -ForegroundColor Yellow
        return
    }
    New-Item -ItemType Directory -Force -Path $PluginsDir | Out-Null
    $src = [System.IO.File]::ReadAllText($PluginSrc)
    $rbxmx = @"
<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4">
	<Item class="Script">
		<Properties>
			<string name="Name">BridgeDefensePersist</string>
			<ProtectedString name="Source"><![CDATA[$src]]></ProtectedString>
			<bool name="Enabled">true</bool>
		</Properties>
	</Item>
</roblox>
"@
    $out = Join-Path $PluginsDir 'BridgeDefensePersist.rbxmx'
    [System.IO.File]::WriteAllText($out, $rbxmx, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Persist plugin installed: $out" -ForegroundColor Green
}

function Start-ProfileDb {
    $logCapture = Join-Path $ProjectRoot 'tools\Start-LogCapture.ps1'
    if (Test-Path -LiteralPath $logCapture) {
        & $logCapture
    } else {
        Start-Process powershell -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $ProjectRoot 'tools\LogServer.ps1')) -WindowStyle Minimized
        Start-Process powershell -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $ProjectRoot 'tools\Watch-Logs.ps1')) -WindowStyle Minimized
    }

    Write-Host 'Waiting for profile DB on :8765 ...' -ForegroundColor Cyan
    $dbReady = $false
    for ($i = 0; $i -lt 30; $i++) {
        try {
            Invoke-WebRequest -Uri 'http://127.0.0.1:8765/profile/0' -Method GET -TimeoutSec 1 -UseBasicParsing -ErrorAction Stop | Out-Null
            $dbReady = $true
            break
        } catch {
            if ($_.Exception.Response -and [int]$_.Exception.Response.StatusCode -eq 404) {
                $dbReady = $true
                break
            }
            Start-Sleep -Milliseconds 400
        }
    }
    if ($dbReady) {
        Write-Host 'Profile DB ready (LogServer :8765 + Watch-Logs)' -ForegroundColor Green
    } else {
        Write-Host 'WARN: Profile DB not responding - Gold/XP may not persist' -ForegroundColor Red
    }
}

Write-Host ''
Write-Host '=== CLEAN RESTART ===' -ForegroundColor Cyan
Write-Host 'Closing old Studio / Rojo / LogServer...' -ForegroundColor Yellow

Get-Process RobloxStudioBeta -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Get-NetTCPConnection -LocalPort 8765 -ErrorAction SilentlyContinue | ForEach-Object {
    Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue
}
Get-NetTCPConnection -LocalPort 34872 -ErrorAction SilentlyContinue | ForEach-Object {
    Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue
}
Get-Process rojo -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Seconds 1

New-Item -ItemType Directory -Force -Path (Join-Path $ProjectRoot 'logs\profiles') | Out-Null
Install-PersistPlugin
Start-ProfileDb

# Перегенерировать StudioProfiles.lua из JSON перед сборкой
$regen = Join-Path $ProjectRoot 'tools\LogServer.ps1'
# LogServer already regenerates on start; ensure module matches JSON
$profileDir = Join-Path $ProjectRoot 'logs\profiles'
$studioProfiles = Join-Path $ProjectRoot 'src\Server\Data\StudioProfiles.lua'
if (Test-Path $profileDir) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('-- Auto-generated by open-studio.ps1. Do not edit.')
    [void]$sb.AppendLine('return {')
    Get-ChildItem $profileDir -Filter '*.json' -ErrorAction SilentlyContinue | ForEach-Object {
        if ($_.BaseName -notmatch '^\d+$') { return }
        $json = [System.IO.File]::ReadAllText($_.FullName).Trim()
        if (-not $json) { return }
        [void]$sb.AppendLine("	[$($_.BaseName)] = [=[")
        [void]$sb.AppendLine($json)
        [void]$sb.AppendLine(']=],')
    }
    [void]$sb.AppendLine('}')
    New-Item -ItemType Directory -Force -Path (Split-Path $studioProfiles) | Out-Null
    [System.IO.File]::WriteAllText($studioProfiles, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
    Write-Host 'StudioProfiles.lua synced from logs\profiles' -ForegroundColor Green
}

$OpenPlace = $null

if ($Live) {
    # Dev: карта из Commission_place + live Rojo (нужен Connect)
    if (Test-Path -LiteralPath $Place2) {
        $OpenPlace = $Place2
    } elseif (Test-Path -LiteralPath $Place1) {
        $OpenPlace = $Place1
        Write-Host 'WARN: Commission_place (2).rbxl missing, using (1)' -ForegroundColor Yellow
    } else {
        Write-Host 'Commission_place (2).rbxl not found.' -ForegroundColor Red
        exit 1
    }
    Write-Host 'Rojo serve (LIVE): commission-place.project.json' -ForegroundColor Cyan
    Start-Process -FilePath $Rojo -ArgumentList @('serve', 'commission-place.project.json') -WorkingDirectory $ProjectRoot -WindowStyle Normal
    Start-Sleep -Seconds 1
} else {
    # Автономно: place уже со скриптами — Connect не нужен
    if ($BuildPackaged -and (Test-Path $Lune)) {
        Write-Host 'Extracting map...' -ForegroundColor Cyan
        Push-Location $ProjectRoot
        & $Lune run tools/extract-commission-map.luau
        Pop-Location
    }
    Write-Host 'Building BridgeDefense_Commission.rbxl (scripts + map + profiles)...' -ForegroundColor Cyan
    Push-Location $ProjectRoot
    & $Rojo build $LobbyProject -o $Packaged
    $buildOk = ($LASTEXITCODE -eq 0)
    Pop-Location
    if (-not $buildOk -or -not (Test-Path -LiteralPath $Packaged)) {
        Write-Host 'ERROR: rojo build failed' -ForegroundColor Red
        exit 1
    }
    $OpenPlace = $Packaged
    Write-Host "Built: $Packaged" -ForegroundColor Green
}

$studio = Get-ChildItem (Join-Path $env:LOCALAPPDATA 'Roblox\Versions') -Recurse -Filter 'RobloxStudioBeta.exe' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if ($studio) {
    $leaf = Split-Path -Leaf $OpenPlace
    Write-Host "Opening: $leaf" -ForegroundColor Cyan
    Start-Process -FilePath $studio.FullName -ArgumentList ('"{0}"' -f $OpenPlace)
} else {
    Write-Host "Roblox Studio not found - open manually: $OpenPlace" -ForegroundColor Yellow
}

Write-Host ''
Write-Host '========================================' -ForegroundColor Green
if ($Live) {
    Write-Host ' LIVE MODE: нужен Plugins → Rojo → Connect' -ForegroundColor Yellow
    Write-Host ' Place: Commission_place + rojo serve' -ForegroundColor Green
} else {
    Write-Host ' АВТОНОМНЫЙ РЕЖИМ (без Connect)' -ForegroundColor Green
    Write-Host ' Place: BridgeDefense_Commission.rbxl' -ForegroundColor Green
    Write-Host ' Скрипты уже внутри place — сразу F5' -ForegroundColor Green
}
Write-Host ' Profile DB: logs\profiles + LogServer :8765' -ForegroundColor Green
Write-Host ' Plugin: BridgeDefensePersist (HTTP auto)' -ForegroundColor Green
Write-Host '========================================' -ForegroundColor Green
Write-Host '1. Дождись загрузки Studio'
Write-Host '2. Нажми F5 (Play)'
Write-Host '3. В Output: DB load OK ... Gold=... и LogServer save OK / Plugin profile saved'
Write-Host '4. Stop можно сразу — сейв идёт на каждый AddGold/autosave'
Write-Host '========================================' -ForegroundColor Green
