-- Auto-generated by LogServer/Watch-Logs. Do not edit.
return {
	[11580620452] = [=[
{"ArmorCopies":[],"Stats":{"TotalKills":188,"TotalWaves":9},"HighestWave":22,"Upgrades":{"XPGain":0,"CritChance":0,"BotDamage":0,"Accuracy":29,"ReloadSpeed":1,"GoldGain":0,"HP":53,"CritDamage":0},"PrestigePoints":0,"OwnedWeapons":{"Crossbow":0,"Shotgun":0,"LMG":0,"SMG":0,"Revolver":0,"Rifle":0,"Sniper":0,"Pistol":2},"TotalXP":53091,"Gold":3284,"Level":29,"XP":2172,"WeaponCopies":{"Pistol":{"1":4,"2":71}},"SquadLoadout":{"1":{"WeaponType":"Pistol","Tier":2},"4":{"WeaponType":"Pistol","Tier":2},"3":{"WeaponType":"Pistol","Tier":2},"2":{"WeaponType":"Pistol","Tier":2}},"DailyReward":{"LastClaimTime":0,"StreakDay":0},"UsedPromocodes":[],"EquippedArmorTier":0,"LastCheckpoint":5,"SquadArmor":{"1":0,"4":0,"3":0,"2":0},"OwnedArmorTier":0,"ActiveBuffs":[],"Ascensions":0}
]=],
}
