-- Auto-generated by LogServer/Watch-Logs. Do not edit.
return {
	[11580620452] = [=[
{"ArmorCopies":{"1":1,"2":1},"Stats":{"TotalKills":1845,"TotalWaves":62},"LastCheckpoint":20,"Upgrades":{"XPGain":0,"CritChance":0,"BotDamage":0,"Accuracy":0,"ReloadSpeed":0,"GoldGain":0,"HP":20,"CritDamage":0},"ActiveBuffs":[],"OwnedWeapons":{"Crossbow":0,"Shotgun":0,"LMG":3,"SMG":0,"Revolver":1,"Rifle":0,"Sniper":0,"Pistol":4},"TotalXP":50627,"UsedPromocodes":[],"Level":29,"XP":48909,"WeaponCopies":{"Revolver":{"1":1},"LMG":{"1":1,"3":2,"2":1},"Pistol":{"1":4,"4":3,"3":1}},"SquadLoadout":{"1":{"WeaponType":"LMG","Tier":3},"4":{"WeaponType":"Pistol","Tier":4},"3":{"WeaponType":"Pistol","Tier":4},"2":{"WeaponType":"LMG","Tier":3}},"DailyReward":{"LastClaimTime":1788601046,"StreakDay":1},"Gold":27930,"EquippedArmorTier":1,"HighestWave":22,"SquadArmor":{"1":2,"4":0,"3":0,"2":1},"OwnedArmorTier":2,"PrestigePoints":0,"Ascensions":0}
]=],
}
