# Watch-Logs.ps1 — Studio Output -> game.log + profile DB (no HttpService needed)
# Looks for: __BD_PROFILE_SAVE__|<userId>|<json>

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$OutFile = Join-Path $ProjectRoot "logs\game.log"
$ProfileDir = Join-Path $ProjectRoot "logs\profiles"
$StudioProfilesLua = Join-Path $ProjectRoot "src\Server\Data\StudioProfiles.lua"
$Filter = "BridgeDefense"
$SaveMarker = "__BD_PROFILE_SAVE__"
$MetaMarker = "__BD_PROFILE_META__"

# Тот же файл, что у LogServer: Add-Content конфликтует — shared append
$script:LogFileLock = New-Object System.Object
function Append-SharedLog {
    param([string]$Path, [string]$Text)
    if (-not $Text) { return }
    $line = if ($Text.EndsWith("`n")) { $Text } else { $Text + "`r`n" }
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($line)
    [System.Threading.Monitor]::Enter($script:LogFileLock)
    try {
        $fs = $null
        try {
            $fs = [System.IO.File]::Open(
                $Path,
                [System.IO.FileMode]::Append,
                [System.IO.FileAccess]::Write,
                [System.IO.FileShare]::ReadWrite
            )
            $fs.Write($bytes, 0, $bytes.Length)
            $fs.Flush()
        } finally {
            if ($fs) { $fs.Dispose() }
        }
    } catch {
        # ignore lock races with LogServer
    } finally {
        [System.Threading.Monitor]::Exit($script:LogFileLock)
    }
}

$logDirs = @(
    "$env:LOCALAPPDATA\Roblox\logs",
    "$env:LOCALAPPDATA\Roblox\Logs"
)

function Get-LatestRobloxLog {
    $latest = $null
    foreach ($dir in $logDirs) {
        if (-not (Test-Path $dir)) { continue }
        $f = Get-ChildItem $dir -Filter "*.log" -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        if ($f -and (-not $latest -or $f.LastWriteTime -gt $latest.LastWriteTime)) {
            $latest = $f
        }
    }
    return $latest
}

function Get-ProfileProgress {
    param($Obj)
    if (-not $Obj) { return @{ TotalXP = -1; HighestWave = -1; Gold = -1 } }
    $xp = 0; $wave = 0; $gold = 0
    try { $xp = [int]$Obj.TotalXP } catch {}
    try { $wave = [int]$Obj.HighestWave } catch {}
    try { $gold = [int]$Obj.Gold } catch {}
    return @{ TotalXP = $xp; HighestWave = $wave; Gold = $gold }
}

function Test-IsStaleProfile {
    param($Incoming, $Existing)
    if (-not $Existing) { return $false }
    $a = Get-ProfileProgress $Incoming
    $b = Get-ProfileProgress $Existing
    if ($a.TotalXP -lt $b.TotalXP) { return $true }
    if ($a.TotalXP -eq $b.TotalXP -and $a.HighestWave -lt $b.HighestWave) { return $true }
    return $false
}

function Write-StudioProfilesModule {
    New-Item -ItemType Directory -Force -Path (Split-Path $StudioProfilesLua) | Out-Null
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("-- Auto-generated by Watch-Logs.ps1 from Studio Output. Do not edit.")
    [void]$sb.AppendLine("return {")
    Get-ChildItem $ProfileDir -Filter "*.json" -ErrorAction SilentlyContinue | ForEach-Object {
        $id = $_.BaseName
        if ($id -notmatch '^\d+$') { return }
        $json = [System.IO.File]::ReadAllText($_.FullName).Trim()
        if (-not $json) { return }
        # long-string level 2 to tolerate ]= in json (unlikely)
        [void]$sb.AppendLine("	[$id] = [=[" )
        [void]$sb.AppendLine($json)
        [void]$sb.AppendLine("]=],")
    }
    [void]$sb.AppendLine("}")
    [System.IO.File]::WriteAllText($StudioProfilesLua, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
}

function Handle-ProfileSaveLine {
    param([string]$Line)
    $idx = $Line.IndexOf($SaveMarker)
    if ($idx -lt 0) { return }
    $payload = $Line.Substring($idx + $SaveMarker.Length)
    if ($payload.StartsWith("|")) { $payload = $payload.Substring(1) }
    $pipe = $payload.IndexOf("|")
    if ($pipe -lt 1) { return }
    $userId = $payload.Substring(0, $pipe).Trim()
    $json = $payload.Substring($pipe + 1).Trim()
    if ($userId -notmatch '^\d+$') { return }
    if (-not $json.StartsWith("{") -or -not $json.EndsWith("}")) { return }
    $incoming = $null
    try { $incoming = $json | ConvertFrom-Json } catch { return }
    if (-not $incoming) { return }
    New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
    $file = Join-Path $ProfileDir "$userId.json"
    $existing = $null
    if (Test-Path $file) {
        try { $existing = Get-Content -Path $file -Raw | ConvertFrom-Json } catch { $existing = $null }
    }
    if (Test-IsStaleProfile -Incoming $incoming -Existing $existing) {
        Write-Host ("Skip stale Output save userId={0} inXP={1} diskXP={2}" -f $userId, $incoming.TotalXP, $existing.TotalXP) -ForegroundColor Yellow
        return
    }
    [System.IO.File]::WriteAllText($file, $json, [System.Text.UTF8Encoding]::new($false))
    Write-StudioProfilesModule
    Write-Host ("Saved profile {0} ({1} bytes) Gold={2} TotalXP={3}" -f $userId, $json.Length, $incoming.Gold, $incoming.TotalXP) -ForegroundColor Green
}

function Handle-ProfileMetaLine {
    param([string]$Line)
    $idx = $Line.IndexOf($MetaMarker)
    if ($idx -lt 0) { return }
    $payload = $Line.Substring($idx + $MetaMarker.Length)
    if ($payload.StartsWith("|")) { $payload = $payload.Substring(1) }
    $parts = $payload.Split("|")
    if ($parts.Count -lt 5) { return }
    $userId = $parts[0].Trim()
    if ($userId -notmatch '^\d+$') { return }
    $gold = 0; $xp = 0; $totalXp = 0; $wave = 0
    [void][int]::TryParse($parts[1], [ref]$gold)
    [void][int]::TryParse($parts[2], [ref]$xp)
    [void][int]::TryParse($parts[3], [ref]$totalXp)
    [void][int]::TryParse($parts[4], [ref]$wave)
    New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null
    $file = Join-Path $ProfileDir "$userId.json"
    $obj = $null
    if (Test-Path $file) {
        try { $obj = $file | Get-Content -Raw | ConvertFrom-Json } catch { $obj = $null }
    }
    if ($obj) {
        $exXp = 0; try { $exXp = [int]$obj.TotalXP } catch {}
        if ($totalXp -lt $exXp) {
            Write-Host ("Skip stale META userId={0} inXP={1} diskXP={2}" -f $userId, $totalXp, $exXp) -ForegroundColor Yellow
            return
        }
        $obj.Gold = $gold
        $obj.XP = $xp
        $obj.TotalXP = $totalXp
        $obj.HighestWave = $wave
    } else {
        $obj = [pscustomobject]@{ Gold = $gold; XP = $xp; TotalXP = $totalXp; HighestWave = $wave; Level = 1 }
    }
    $json = $obj | ConvertTo-Json -Compress -Depth 20
    [System.IO.File]::WriteAllText($file, $json, [System.Text.UTF8Encoding]::new($false))
    Write-StudioProfilesModule
    Write-Host ("Patched Gold/XP userId={0} Gold={1} TotalXP={2}" -f $userId, $gold, $totalXp) -ForegroundColor Green
}

New-Item -ItemType Directory -Force -Path (Split-Path $OutFile) | Out-Null
New-Item -ItemType Directory -Force -Path $ProfileDir | Out-Null

if (-not (Test-Path $OutFile)) {
    [System.IO.File]::WriteAllText(
        $OutFile,
        "=== Studio watch -> game.log started $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ===`r`n",
        [System.Text.UTF8Encoding]::new($false)
    )
} else {
    Append-SharedLog -Path $OutFile -Text "`r`n--- Studio watch restarted $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') ---"
}

# Seed module from existing json files
Write-StudioProfilesModule

Write-Host "Watching Roblox Studio Output -> $OutFile" -ForegroundColor Cyan
Write-Host "Profile DB via Output marker $SaveMarker" -ForegroundColor Cyan

$currentFile = $null
$lastSize = 0

while ($true) {
    $latest = Get-LatestRobloxLog
    if ($latest) {
        if (-not $currentFile -or $currentFile.FullName -ne $latest.FullName) {
            $currentFile = $latest
            $lastSize = [Math]::Max(0, $latest.Length - 256kb)
            Append-SharedLog -Path $OutFile -Text "--- Source: $($latest.FullName) ---"
        }

        if ($latest.Length -gt $lastSize) {
            $stream = [System.IO.File]::Open($latest.FullName, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
            $stream.Seek($lastSize, [System.IO.SeekOrigin]::Begin) | Out-Null
            $reader = New-Object System.IO.StreamReader($stream)
            while (-not $reader.EndOfStream) {
                $line = $reader.ReadLine()
                if (-not $line) { continue }
                if ($line.Contains($SaveMarker)) {
                    Handle-ProfileSaveLine -Line $line
                    Append-SharedLog -Path $OutFile -Text $line
                } elseif ($line.Contains($MetaMarker)) {
                    Handle-ProfileMetaLine -Line $line
                    Append-SharedLog -Path $OutFile -Text $line
                } elseif ($line.Contains($Filter)) {
                    Append-SharedLog -Path $OutFile -Text $line
                }
            }
            $lastSize = $stream.Position
            $reader.Close()
            $stream.Close()
        }
    }
    Start-Sleep -Milliseconds 500
}
